apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cell-schatty
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: bucket-app
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector/bench-cell
        value: schatty
      - op: replace
        path: /spec/template/spec/tolerations/0/value
        value: schatty
      - op: replace
        path: /spec/template/spec/containers/0/env/2
        value:
          name: BENCH_PRESET
          value: S
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: BENCH_JDBC_OPS
          value: "1"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: BENCH_REDIS_OPS
          value: "0"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: BENCH_HTTP_CALLS
          value: "0"
  - target:
      kind: Deployment
      labelSelector: bench-role=deps
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector/bench-deps
        value: schatty
      - op: replace
        path: /spec/template/spec/tolerations/0/value
        value: schatty
